apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: apigo:alpha
          envFrom:
            - secretRef:
                name: {{ printf "%s-secret" .Values.dbName }}
          imagePullPolicy: Never   # Important: don't try to pull from Docker Hub
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Values.appName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 30100
