apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigo
  template:
    metadata:
      labels:
        app: apigo
    spec:
      containers:
        - name: apigo
          image: apigo:alpha
          imagePullPolicy: Never   # Important: don't try to pull from Docker Hub
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apigo-service
spec:
  type: NodePort
  selector:
    app: apigo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
