apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: bXl1c2Vy        # myuser
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # mypassword
  POSTGRES_DB: bXlkYg==          # mydb